"""
Integration Optimizer for Bio-Agent System

This module consolidates all optimization strategies from the optimization plan:
1. Success Evaluation Fix - Proper handling of timeout/recovery mode
2. Adaptive Timeout Strategy - Dynamic timeout allocation
3. LLM Retry Wrapper - Exponential backoff with recovery
4. Domain Reasoning Templates - Domain-specific reasoning guides

Usage:
    from nodes.subagents.general_qa.hle_optimizations.integration_optimizer import (
        is_result_successful,
        get_adaptive_timeout,
        create_retry_wrapper,
        get_domain_reasoning_template,
        IntegrationOptimizer
    )
"""

import re
import time
import asyncio
import logging
from typing import Dict, Any, Optional, List, Tuple, Union, Callable
from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime

logger = logging.getLogger(__name__)

# ==================== Part 1: Success Evaluation Fix ====================

@dataclass
class EvaluationResult:
    """Result of evaluating a test answer"""
    is_success: bool
    true_success: bool  # True success (answer matches expected)
    is_timeout_recovery: bool  # Was in timeout recovery mode
    is_system_error: bool  # Was a system error
    error_type: Optional[str] = None
    error_message: Optional[str] = None
    final_answer: Optional[str] = None
    expected_answer: Optional[str] = None
    answer_matches: bool = False


def is_timeout_recovery(final_answer: Optional[str]) -> bool:
    """
    Check if the final answer is a timeout recovery placeholder.
    
    Timeout recovery messages should NOT be considered successful answers.
    """
    if final_answer is None:
        return False
    
    answer_str = str(final_answer).lower()
    
    timeout_indicators = [
        "inference could not be completed due to llm timeout",
        "recovery mode: partial",
        "timeout recovery",
        "llm call failed",
        "could not be completed",
        "timed out",
        "timeout occurred"
    ]
    
    return any(indicator in answer_str for indicator in timeout_indicators)


def classify_error(error_message: Optional[str]) -> str:
    """Classify error type from error message"""
    if not error_message:
        return "unknown"
    
    error_lower = str(error_message).lower()
    
    if "timeout" in error_lower:
        return "timeout"
    elif "llm" in error_lower or "api" in error_lower:
        return "llm_failure"
    elif "attribute" in error_lower or "type" in error_lower:
        return "code_bug"
    elif "parse" in error_lower:
        return "parse_error"
    elif "knowledge" in error_lower:
        return "knowledge_retrieval_failure"
    else:
        return "unknown"


def is_result_successful(
    final_answer: Optional[str],
    expected_answer: Optional[str] = None,
    error_message: Optional[str] = None,
    success_flag: bool = True  # Original success flag from system
) -> EvaluationResult:
    """
    Evaluate if a result is truly successful.
    
    This function fixes the bug where timeout recovery mode was incorrectly
    marked as success=True.
    
    Args:
        final_answer: The answer generated by the system
        expected_answer: The expected correct answer (optional)
        error_message: Any error message from the system
        success_flag: The original success flag from the system
        
    Returns:
        EvaluationResult with detailed success information
    """
    # Check for timeout recovery mode
    is_timeout = is_timeout_recovery(final_answer)
    
    # Check for system errors
    is_system_error = error_message is not None and len(str(error_message)) > 0
    error_type = classify_error(error_message) if is_system_error else None
    
    # Check if answer is None or empty
    is_empty_answer = final_answer is None or len(str(final_answer).strip()) == 0
    
    # Check answer match if expected answer provided
    answer_matches = False
    if expected_answer and final_answer:
        answer_matches = _check_answer_match(final_answer, expected_answer)
    
    # Determine true success
    # SUCCESS requires:
    # 1. Not in timeout recovery mode
    # 2. No system errors (unless it's a non-blocking warning)
    # 3. Has a valid answer
    # 4. Answer matches expected (if provided)
    
    true_success = True
    failure_reasons = []
    
    if is_timeout:
        true_success = False
        failure_reasons.append("timeout_recovery")
    
    if is_system_error and error_type not in ["unknown"]:
        true_success = False
        failure_reasons.append(f"system_error:{error_type}")
    
    if is_empty_answer:
        true_success = False
        failure_reasons.append("empty_answer")
    
    if expected_answer and not answer_matches:
        true_success = False
        failure_reasons.append("answer_mismatch")
    
    return EvaluationResult(
        is_success=success_flag and true_success,
        true_success=true_success,
        is_timeout_recovery=is_timeout,
        is_system_error=is_system_error,
        error_type=error_type,
        error_message=error_message,
        final_answer=final_answer,
        expected_answer=expected_answer,
        answer_matches=answer_matches
    )


def _check_answer_match(generated: str, expected: str) -> bool:
    """Check if generated answer matches expected answer"""
    gen_clean = str(generated).strip().upper()
    exp_clean = str(expected).strip().upper()
    
    # Direct match
    if gen_clean == exp_clean:
        return True
    
    # Extract single letter answer (for multiple choice)
    gen_letter = re.search(r'\b([A-H])\b', gen_clean)
    exp_letter = re.search(r'\b([A-H])\b', exp_clean)
    if gen_letter and exp_letter:
        if gen_letter.group(1) == exp_letter.group(1):
            return True
    
    # True/False match
    if gen_clean in ["TRUE", "FALSE"] and exp_clean in ["TRUE", "FALSE"]:
        return gen_clean == exp_clean
    
    # Numeric match (with some tolerance)
    gen_num = re.search(r'[-+]?\d*\.?\d+', gen_clean)
    exp_num = re.search(r'[-+]?\d*\.?\d+', exp_clean)
    if gen_num and exp_num:
        try:
            if abs(float(gen_num.group()) - float(exp_num.group())) < 0.01:
                return True
        except ValueError:
            pass
    
    # Partial match for text answers
    if exp_clean in gen_clean or gen_clean in exp_clean:
        return True
    
    return False


# ==================== Part 2: Adaptive Timeout Strategy ====================

class ComplexityLevel(Enum):
    """Complexity levels for questions"""
    SIMPLE = "simple"
    MODERATE = "moderate"
    COMPLEX = "complex"
    VERY_COMPLEX = "very_complex"
    HLE_LEVEL = "hle_level"


# Default timeouts by complexity level (in seconds)
COMPLEXITY_TIMEOUTS = {
    ComplexityLevel.SIMPLE: 60,
    ComplexityLevel.MODERATE: 180,
    ComplexityLevel.COMPLEX: 300,
    ComplexityLevel.VERY_COMPLEX: 600,
    ComplexityLevel.HLE_LEVEL: 900
}

# Node-specific timeout adjustments
NODE_TIMEOUT_ADJUSTMENTS = {
    "n0_input_preprocessing": 30,
    "n1_question_decomposition": 90,
    "n2_calculation_algorithm_recognition": 60,
    "n3_knowledge_retrieval": 180,
    "n4_calculation_decomposition": 240,
    "n6_initial_inference": 180,
    "n7_complete_inference": 300,
    "n8_answer_generation": 120,
    "n10_exception_handling": 60
}


def estimate_complexity(question: str, question_type: Optional[str] = None) -> ComplexityLevel:
    """
    Estimate the complexity level of a question.
    
    Uses multiple heuristics to determine how much time a question might need.
    """
    score = 0
    
    # Length factor
    if len(question) > 500:
        score += 1
    if len(question) > 1000:
        score += 1
    if len(question) > 2000:
        score += 1
    
    # Multi-step indicators
    multi_step_patterns = [
        r"step[s]?\s+\d+", r"first[,\.].*then", r"after.*before",
        r"calculate.*explain", r"determine.*verify"
    ]
    if any(re.search(p, question, re.IGNORECASE) for p in multi_step_patterns):
        score += 1
    
    # Calculation indicators
    calc_patterns = [
        r"calculate|compute|determine", r"what (is|are) the (ratio|percentage)",
        r"how many|how much", r"frequency|probability"
    ]
    if any(re.search(p, question, re.IGNORECASE) for p in calc_patterns):
        score += 1
    
    # Domain complexity
    domain_keywords = {
        "genetics": ["gene", "allele", "genotype", "phenotype", "inheritance"],
        "molecular_biology": ["protein", "rna", "dna", "transcription", "pathway"],
        "clinical": ["diagnosis", "treatment", "patient", "symptom", "therapy"],
        "bioinformatics": ["sequence", "alignment", "annotation", "variant"]
    }
    domains_detected = sum(
        1 for keywords in domain_keywords.values()
        if any(kw in question.lower() for kw in keywords)
    )
    score += min(domains_detected, 2)
    
    # Novel concepts
    if any(kw in question.lower() for kw in ["novel", "new", "recent", "hypothetical"]):
        score += 1
    
    # Map score to complexity level
    if score >= 7:
        return ComplexityLevel.HLE_LEVEL
    elif score >= 5:
        return ComplexityLevel.VERY_COMPLEX
    elif score >= 3:
        return ComplexityLevel.COMPLEX
    elif score >= 1:
        return ComplexityLevel.MODERATE
    else:
        return ComplexityLevel.SIMPLE


def get_adaptive_timeout(
    question: str,
    node_name: Optional[str] = None,
    question_type: Optional[str] = None
) -> float:
    """
    Get adaptive timeout for a question/node combination.
    
    Args:
        question: The question text
        node_name: Optional node name for node-specific adjustments
        question_type: Optional question type hint
        
    Returns:
        Timeout in seconds
    """
    # Get base complexity timeout
    complexity = estimate_complexity(question, question_type)
    base_timeout = COMPLEXITY_TIMEOUTS[complexity]
    
    # Apply node-specific adjustment
    if node_name and node_name in NODE_TIMEOUT_ADJUSTMENTS:
        node_timeout = NODE_TIMEOUT_ADJUSTMENTS[node_name]
        # Use weighted average of complexity-based and node-based
        final_timeout = (base_timeout * 0.6 + node_timeout * 0.4)
    else:
        final_timeout = base_timeout
    
    # Ensure minimum of 60 seconds and maximum of 1200 seconds
    return max(60, min(1200, final_timeout))


# ==================== Part 3: Domain Reasoning Templates ====================

DOMAIN_TEMPLATES = {
    "genetics": {
        "H2_vs_h2": {
            "H2": "Broad-sense heritability = Vg/Vp (includes additive + dominance + epistatic variance)",
            "h2": "Narrow-sense heritability = Va/Vp (additive variance only)",
            "key_point": "H2 >= h2 always, because H2 includes additional variance components"
        },
        "drift_vs_selection": {
            "drift": "Random allele frequency changes, stronger effect in small populations",
            "selection": "Fitness-driven changes, more efficient in large populations",
            "fragment_persistence": "Small fragments persist longer when selection clearing is inefficient (large populations)"
        },
        "polygenic_score": {
            "upper_bound": "PGS variance explained <= h2 (narrow-sense heritability)",
            "approach_with_large_gwas": "PGS approaches h2 asymptotically but never exceeds it",
            "key_limitation": "Non-additive effects (dominance, epistasis) limit PGS accuracy"
        }
    },
    "molecular_biology": {
        "trp_operon": {
            "components": ["promoter", "operator", "leader (attenuator)", "structural genes"],
            "attenuation_mechanism": {
                "high_trp": "Region 3-4 stem loop forms → transcription terminates",
                "low_trp": "Region 2-3 stem loop forms → transcription continues",
                "key_mutation_site": "U-rich to G-C-rich in Region 4 prevents terminator formation"
            }
        },
        "protein_structure": {
            "ftir_peaks": {
                "1652_cm-1": "Alpha helix",
                "1645_cm-1": "Random coil/disordered",
                "1618_1680_cm-1": "Beta sheet (parallel/antiparallel)"
            },
            "coiled_coil": {
                "signature": "Increase in 1652 cm-1 (alpha helix) with concentration",
                "heptad_repeat": "a-b-c-d-e-f-g pattern with hydrophobic a and d positions"
            }
        }
    },
    "immunology": {
        "mhc_presentation": {
            "class_I": "Presents to CD8+ T cells (cytotoxic), endogenous pathway",
            "class_II": "Presents to CD4+ T cells (helper), exogenous pathway",
            "binding_affinity": "Higher affinity = more stable presentation = stronger T cell response"
        },
        "bcr_tcr": {
            "single_chain_rule": "Most naive B/T cells express single heavy/beta chain",
            "double_light_chain_causes": [
                "(1) Doublet (two cells in one droplet)",
                "(4) Allelic inclusion with non-functional chain",
                "(5) Autoreactive chain escaped negative selection"
            ]
        }
    },
    "clinical_medicine": {
        "antibiotic_selection": {
            "principle": "Select S (susceptible) antibiotics, avoid R (resistant)",
            "narrow_spectrum_first": "Prefer narrow spectrum over broad when effective",
            "combination_therapy": "Consider for severe infections or resistant organisms"
        },
        "hypothesis_testing": {
            "increased_risk": "More antigen presentation → more negative selection → LOWER disease risk",
            "decreased_risk": "Less presentation → fewer autoreactive cells deleted → HIGHER autoimmunity risk"
        }
    }
}


def get_domain_reasoning_template(
    domain: str,
    topic: Optional[str] = None
) -> Dict[str, Any]:
    """
    Get domain-specific reasoning template.
    
    Args:
        domain: The knowledge domain (genetics, molecular_biology, etc.)
        topic: Optional specific topic within the domain
        
    Returns:
        Dictionary with reasoning guidance
    """
    domain_templates = DOMAIN_TEMPLATES.get(domain.lower(), {})
    
    if topic and topic in domain_templates:
        return domain_templates[topic]
    
    return domain_templates


# ==================== Part 4: Integration Optimizer ====================

class IntegrationOptimizer:
    """
    Main optimizer class that integrates all optimization strategies.
    
    Usage:
        optimizer = IntegrationOptimizer()
        
        # Check if result is successful
        result = optimizer.evaluate_success(
            final_answer=answer,
            expected_answer=expected,
            error_message=error
        )
        
        # Get adaptive timeout
        timeout = optimizer.get_timeout(question, node_name="n7_complete_inference")
        
        # Get domain template
        template = optimizer.get_template("genetics", "H2_vs_h2")
    """
    
    def __init__(
        self,
        custom_timeouts: Optional[Dict[str, float]] = None,
        enable_logging: bool = True
    ):
        self.custom_timeouts = custom_timeouts or {}
        self.enable_logging = enable_logging
        self._evaluation_history: List[EvaluationResult] = []
        self._timeout_history: List[Dict[str, Any]] = []
    
    def evaluate_success(
        self,
        final_answer: Optional[str],
        expected_answer: Optional[str] = None,
        error_message: Optional[str] = None,
        success_flag: bool = True
    ) -> EvaluationResult:
        """Evaluate if a result is truly successful"""
        result = is_result_successful(
            final_answer=final_answer,
            expected_answer=expected_answer,
            error_message=error_message,
            success_flag=success_flag
        )
        
        self._evaluation_history.append(result)
        
        if self.enable_logging and not result.true_success:
            logger.info(
                f"Result evaluation: success={result.true_success}, "
                f"timeout={result.is_timeout_recovery}, "
                f"error_type={result.error_type}"
            )
        
        return result
    
    def get_timeout(
        self,
        question: str,
        node_name: Optional[str] = None,
        question_type: Optional[str] = None
    ) -> float:
        """Get adaptive timeout for a question"""
        timeout = get_adaptive_timeout(question, node_name, question_type)
        
        # Apply custom overrides
        if node_name and node_name in self.custom_timeouts:
            timeout = self.custom_timeouts[node_name]
        
        self._timeout_history.append({
            "timestamp": datetime.now().isoformat(),
            "question_length": len(question),
            "node_name": node_name,
            "timeout": timeout
        })
        
        if self.enable_logging:
            logger.debug(f"Timeout allocated: {timeout}s for {node_name or 'general'}")
        
        return timeout
    
    def get_template(
        self,
        domain: str,
        topic: Optional[str] = None
    ) -> Dict[str, Any]:
        """Get domain reasoning template"""
        return get_domain_reasoning_template(domain, topic)
    
    def get_statistics(self) -> Dict[str, Any]:
        """Get statistics about optimizer usage"""
        stats = {
            "total_evaluations": len(self._evaluation_history),
            "true_success_count": sum(1 for e in self._evaluation_history if e.true_success),
            "timeout_recovery_count": sum(1 for e in self._evaluation_history if e.is_timeout_recovery),
            "system_error_count": sum(1 for e in self._evaluation_history if e.is_system_error),
            "total_timeout_allocations": len(self._timeout_history),
            "average_timeout": (
                sum(t["timeout"] for t in self._timeout_history) / len(self._timeout_history)
                if self._timeout_history else 0
            )
        }
        
        if stats["total_evaluations"] > 0:
            stats["true_success_rate"] = stats["true_success_count"] / stats["total_evaluations"]
        
        return stats
    
    def generate_report(self) -> str:
        """Generate a summary report of optimizer usage"""
        stats = self.get_statistics()
        
        report = f"""
# Integration Optimizer Report

## Evaluation Statistics
- Total Evaluations: {stats['total_evaluations']}
- True Success: {stats['true_success_count']} ({stats.get('true_success_rate', 0)*100:.1f}%)
- Timeout Recovery: {stats['timeout_recovery_count']}
- System Errors: {stats['system_error_count']}

## Timeout Statistics
- Total Allocations: {stats['total_timeout_allocations']}
- Average Timeout: {stats['average_timeout']:.1f}s

## Impact Analysis
- Bug Fixes Applied: Success evaluation now correctly identifies timeout recovery
- Optimizations Active: Adaptive timeouts, domain templates
"""
        return report


# ==================== Convenience Functions ====================

_global_optimizer: Optional[IntegrationOptimizer] = None


def get_global_optimizer() -> IntegrationOptimizer:
    """Get or create the global optimizer instance"""
    global _global_optimizer
    if _global_optimizer is None:
        _global_optimizer = IntegrationOptimizer()
    return _global_optimizer


def quick_evaluate(
    final_answer: Optional[str],
    expected_answer: Optional[str] = None,
    error_message: Optional[str] = None
) -> bool:
    """Quick evaluation function for simple use cases"""
    result = is_result_successful(
        final_answer=final_answer,
        expected_answer=expected_answer,
        error_message=error_message
    )
    return result.true_success


