from typing import Dict, List, Any, Optional, TYPE_CHECKING, ForwardRef, Callable
from pydantic import BaseModel, Field, ConfigDict
from enum import Enum
from datetime import datetime

if TYPE_CHECKING:
    from nodes.subagents.code_act.todo_list import TodoList

# 运行时占位符 - 在 ensure_global_state_rebuilt() 调用后会被替换为真实的 TodoList 类
# 这是为了让 get_type_hints() 在解析前向引用时能找到 "TodoList"
TodoList = None


# User task type enum
class UserTaskType(str, Enum):
    """User task type"""

    GENERAL_QA = "GENERAL_QA"
    EXECUTE_PLAN = "EXECUTE_PLAN"
    IMMUNOLOGY_TASK = "IMMUNOLOGY_TASK"
    USE_HISTORY = "USE_HISTORY"


# Task status enum
class TaskStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    DEPENDENCY_WAIT = "dependency_wait"


# Parameter source enum - tracks where a parameter value came from
class ParameterSource(str, Enum):
    """Parameter source type for tracking parameter origin"""

    USER_INPUT = "user_input"  # Provided by user during preprocessing
    TASK_OUTPUT = "task_output"  # Generated by a task execution
    INFERRED = "inferred"  # Inferred by LLM from context
    DEFAULT = "default"  # Default value from tool definition


# Tagged parameter value - stores value with its source information
class TaggedParameterValue(BaseModel):
    """A parameter value with source tracking"""

    value: Any = Field(description="The actual parameter value")
    source: ParameterSource = Field(description="Where this value came from")
    source_task_id: Optional[str] = Field(
        default=None, description="Task ID if source is TASK_OUTPUT"
    )
    description: Optional[str] = Field(
        default=None, description="Human-readable description of the parameter"
    )
    data_type: Optional[str] = Field(
        default=None,
        description="Data type hint (e.g., 'binding_predictions', 'airr_results')",
    )

    def __str__(self) -> str:
        return str(self.value)

    def __repr__(self) -> str:
        return f"TaggedValue({self.value}, source={self.source.value})"


# Single task model (added parallel_group_id to associate dependent parallel task groups)
class SubTask(BaseModel):
    model_config = ConfigDict(use_enum_values=True)

    task_id: str = Field(description="Unique task ID")
    task_type: UserTaskType = Field(description="Task type")
    content: str = Field(description="Task content")
    dependencies: List[str] = Field(
        default_factory=list, description="Dependent regular task IDs"
    )
    parallel_group_id: Optional[str] = Field(
        default=None, description="Dependent parallel task group ID"
    )
    result: Optional[Any] = Field(default=None, description="Task result")


# Parallel task group model (contains multiple parallel subtasks)
class ParallelTaskGroup(BaseModel):
    group_id: str = Field(
        description="Parallel task group ID (for dependent task association)"
    )
    subtasks: List[SubTask] = Field(description="Parallel subtasks within group")
    status: TaskStatus = Field(
        default=TaskStatus.PENDING, description="Overall group status"
    )


# Global state class
class GlobalState(BaseModel):
    model_config = ConfigDict(
        use_enum_values=True,
        arbitrary_types_allowed=True,
    )

    user_input: str = Field(description="User's original input")
    user_task_type: Optional[UserTaskType] = Field(
        default=None, description="User task type"
    )
    subtasks: List[SubTask] = Field(
        default_factory=list, description="Regular subtask list"
    )
    parallel_task_groups: Dict[str, ParallelTaskGroup] = Field(
        default_factory=dict, description="Parallel task groups (key=group_id)"
    )
    completed_tasks: Dict[str, SubTask] = Field(
        default_factory=dict, description="Completed regular tasks"
    )
    completed_parallel_groups: Dict[str, ParallelTaskGroup] = Field(
        default_factory=dict, description="Completed parallel task groups"
    )
    merged_result: Dict[str, Any] = Field(
        default_factory=dict, description="Merged results"
    )
    hitl_status: Optional[str] = Field(default=None, description="HITL status")
    file_paths: Dict[str, str] = Field(default_factory=dict, description="File paths")
    execution_plan: Optional[str] = Field(default=None, description="Execution plan")
    sandbox_dir: str = Field(description="Sandbox directory")
    use_react_executor: bool = Field(
        default=False, description="Use React executor for single task execution"
    )
    react_max_steps: int = Field(
        default=3, description="Max React executor steps per task"
    )
    use_react_supervisor: bool = Field(
        default=False, description="Use React supervisor for task classification"
    )
    supervisor_decision: Optional[str] = Field(
        default=None, description="Supervisor decision label"
    )
    supervisor_reasoning: Optional[str] = Field(
        default=None, description="Supervisor reasoning"
    )

    # CodeAct Todo List - for executor subgraph integration
    todo_list: Optional["TodoList"] = Field(
        default=None, description="CodeAct todo list for task execution"
    )

    # Preprocessing results - parameter table for the entire workflow
    session_id: Optional[str] = Field(
        default=None, description="Unique session ID for file management"
    )
    opensandbox_id: Optional[str] = Field(
        default=None, description="OpenSandbox instance ID"
    )
    sandbox_data_dir: Optional[str] = Field(
        default=None, description="Data directory in sandbox"
    )
    extracted_parameters: Dict[str, Any] = Field(
        default_factory=dict, description="Parameter table extracted from user input"
    )
    file_analyses: List[Dict[str, Any]] = Field(
        default_factory=list, description="File analysis results"
    )

    # ==================== Iterative Executor 新增字段 ====================

    # 迭代执行历史记录
    iteration_history: List[Dict[str, Any]] = Field(
        default_factory=list, description="迭代执行历史记录 (由 IterativeExecutor 生成)"
    )

    # 已完成的输出文件列表
    completed_output_files: List[str] = Field(
        default_factory=list, description="已完成的输出文件路径列表"
    )

    # MCP 工具调用记录
    mcp_call_records: List[Dict[str, Any]] = Field(
        default_factory=list, description="MCP 工具调用记录"
    )

    # Thinking 历史记录 - 用于跟踪 LLM thinking 过程
    thinking_history: List[Dict[str, Any]] = Field(
        default_factory=list, description="LLM thinking 过程历史记录"
    )

    # ==================== Init Node 新增字段 ====================

    # 已上传到共享目录的文件列表
    uploaded_files: List[str] = Field(
        default_factory=list, description="已上传到沙盒共享目录的文件路径列表"
    )

    # 对话消息记录（从关系型数据库加载）
    conversation_history: List[Dict[str, Any]] = Field(
        default_factory=list, description="对话消息记录"
    )

    # Mem0 任务历史
    immunity_history: List[Dict[str, Any]] = Field(
        default_factory=list, description="Mem0 中该 session 的历史任务结果"
    )

    # ==================== HITL (Human-in-the-Loop) 新增字段 ====================

    # HITL 迭代计数器
    hitl_iteration: int = Field(default=0, description="HITL 迭代次数计数器")

    # 用户反馈内容
    user_feedback: Optional[str] = Field(default=None, description="用户反馈内容")

    # 缺失的参数
    missing_parameters: List[Dict[str, Any]] = Field(
        default_factory=list, description="缺失的参数"
    )

    # HITL 确认状态
    hitl_confirmed: bool = Field(default=False, description="HITL 用户确认状态")

    # HITL 请求数据
    hitl_request: Optional[Dict[str, Any]] = Field(
        default=None, description="HITL 请求数据"
    )

    # HITL 历史记录
    hitl_history: List[Dict[str, Any]] = Field(
        default_factory=list, description="HITL 历史记录"
    )

    # HITL 请求数据历史
    hitl_request_history: List[Dict[str, Any]] = Field(
        default_factory=list, description="HITL 请求数据历史"
    )

    # HITL 请求数据列表
    hitl_requests: List[Dict[str, Any]] = Field(
        default_factory=list, description="HITL 请求数据列表"
    )

    # HITL 响应数据
    hitl_response: Optional[Dict[str, Any]] = Field(
        default=None, description="HITL 响应数据"
    )

    # HITL 响应数据历史
    hitl_response_history: List[Dict[str, Any]] = Field(
        default_factory=list, description="HITL 响应数据历史"
    )

    # HITL 响应数据列表
    hitl_responses: List[Dict[str, Any]] = Field(
        default_factory=list, description="HITL 响应数据列表"
    )

    # 父状态（用于子图）
    parent_state: Optional["GlobalState"] = Field(
        default=None, description="父状态（用于子图）"
    )

    # 任务 markdown 内容
    task_md_content: Optional[str] = Field(
        default=None, description="任务 markdown 内容"
    )

    def get_llm(
        self, purpose: str = "reasoning", node_name: Optional[str] = None, **kwargs
    ) -> Optional[Any]:
        """
        获取 LLM 实例（推荐方法）

        自动使用 self.progress_callback 和 self.session_id 创建 LLM，
        确保所有 thinking 都能被正确捕获和推送。

        Args:
            purpose: 模型用途，可选: "reasoning", "bioinformatics", "reasoning_advanced", "code"
            node_name: 节点名称，如果不提供会自动推断
            **kwargs: 传递给 LLM 创建函数的其他参数

        Returns:
            LLM 实例，如果创建失败则返回 None

        Examples:
            >>> llm = state.get_llm(purpose="reasoning", node_name="supervisor")
            >>> response = llm.invoke(messages)
        """
        from agent.utils.llm_factory import create_llm_with_thinking

        # 自动推断节点名称
        if node_name is None:
            node_name = self._get_caller_node_name()

        # 通过session_id从全局registry获取callback
        callback = None
        if self.session_id:
            try:
                import sys
                from pathlib import Path

                backend_dir = Path(__file__).parent.parent / "backend"
                project_root = backend_dir.parent

                if str(backend_dir) not in sys.path:
                    sys.path.insert(0, str(backend_dir))
                if str(project_root) not in sys.path:
                    sys.path.insert(0, str(project_root))

                from backend import progress_tracker as pt_module

                callback = pt_module.get_progress_callback(self.session_id)
                print(
                    f"[GlobalState.get_llm] Got callback for session {self.session_id}: {callback is not None}"
                )
            except (ImportError, AttributeError) as e:
                print(f"[GlobalState.get_llm] Failed to get callback: {e}")

        return create_llm_with_thinking(
            purpose=purpose,
            progress_callback=callback,
            session_id=self.session_id,
            node_name=node_name,
            **kwargs,
        )

    def _get_caller_node_name(self) -> str:
        """
        自动推断调用者节点名称

        通过检查调用栈来推断节点名称，如果函数名以 '_node' 结尾，
        则返回去掉 '_node' 后的名称。

        Returns:
            推断的节点名称
        """
        import inspect

        try:
            frame = inspect.currentframe()
            if frame and frame.f_back and frame.f_back.f_back:
                func_name = frame.f_back.f_back.f_code.co_name
                if func_name.endswith("_node"):
                    return func_name.replace("_node", "")
        except Exception:
            pass
        return "unknown"

    def record_thinking(
        self,
        content: str,
        node_name: str,
        step_name: str = "推理",
        details: Optional[Dict[str, Any]] = None,
    ) -> None:
        """
        记录 thinking 到历史

        将 LLM thinking 过程记录到 thinking_history 字段，
        方便后续查询和调试。

        Args:
            content: Thinking 内容
            node_name: 节点名称
            step_name: 步骤名称
            details: 其他详细信息
        """
        record = {
            "timestamp": datetime.now().isoformat(),
            "node": node_name,
            "step": step_name,
            "content": content[:500] if len(content) > 500 else content,
            "session_id": self.session_id,
        }
        if details:
            record["details"] = details

        self.thinking_history.append(record)


# Lazy rebuild of GlobalState to resolve forward references (Pydantic v2 requirement)
# This is called when the todo_list field is first accessed with a TodoList object
_global_state_rebuilt = False


def ensure_global_state_rebuilt() -> None:
    """
    Ensure GlobalState model is rebuilt to resolve forward references.

    This must be called before using the todo_list field with a TodoList object.
    It's safe to call multiple times - subsequent calls are no-ops.

    Note: This also injects TodoList into the module's global namespace so that
    get_type_hints() can resolve the forward reference "TodoList" in GlobalState.
    """
    global _global_state_rebuilt, TodoList
    if _global_state_rebuilt:
        return

    try:
        from nodes.subagents.code_act.todo_list import TodoList as _TodoList

        # 将 TodoList 注入到模块的全局命名空间，让 get_type_hints() 能解析前向引用
        globals()["TodoList"] = _TodoList
        TodoList = _TodoList
        GlobalState.model_rebuild()
        _global_state_rebuilt = True
    except ImportError as e:
        # If TodoList cannot be imported, log warning but continue
        # The model will work but todo_list field will only accept dicts
        import warnings

        warnings.warn(f"Could not rebuild GlobalState with TodoList: {e}")


# Note: We don't call ensure_global_state_rebuilt() here to avoid import-time side effects.
# Instead, code that needs to use the todo_list field should call it explicitly.
