from typing import Dict, List, Any, Optional, TYPE_CHECKING, ForwardRef, Callable
from pydantic import BaseModel, Field, ConfigDict
from enum import Enum
from datetime import datetime

if TYPE_CHECKING:
    from nodes.subagents.code_act.todo_list import TodoList

# Runtime placeholder - replaced with real TodoList class after ensure_global_state_rebuilt() is called
# This allows get_type_hints() to resolve the "TodoList" forward reference
TodoList = None


# User task type enum
class UserTaskType(str, Enum):
    """User task type"""

    GENERAL_QA = "GENERAL_QA"
    EXECUTE_PLAN = "EXECUTE_PLAN"
    IMMUNOLOGY_TASK = "IMMUNOLOGY_TASK"
    USE_HISTORY = "USE_HISTORY"


# Task status enum
class TaskStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    DEPENDENCY_WAIT = "dependency_wait"


# Parameter source enum - tracks where a parameter value came from
class ParameterSource(str, Enum):
    """Parameter source type for tracking parameter origin"""

    USER_INPUT = "user_input"  # Provided by user during preprocessing
    TASK_OUTPUT = "task_output"  # Generated by a task execution
    INFERRED = "inferred"  # Inferred by LLM from context
    DEFAULT = "default"  # Default value from tool definition


# Tagged parameter value - stores value with its source information
class TaggedParameterValue(BaseModel):
    """A parameter value with source tracking"""

    value: Any = Field(description="The actual parameter value")
    source: ParameterSource = Field(description="Where this value came from")
    source_task_id: Optional[str] = Field(
        default=None, description="Task ID if source is TASK_OUTPUT"
    )
    description: Optional[str] = Field(
        default=None, description="Human-readable description of the parameter"
    )
    data_type: Optional[str] = Field(
        default=None,
        description="Data type hint (e.g., 'binding_predictions', 'airr_results')",
    )

    def __str__(self) -> str:
        return str(self.value)

    def __repr__(self) -> str:
        return f"TaggedValue({self.value}, source={self.source.value})"


# Single task model (added parallel_group_id to associate dependent parallel task groups)
class SubTask(BaseModel):
    model_config = ConfigDict(use_enum_values=True)

    task_id: str = Field(description="Unique task ID")
    task_type: UserTaskType = Field(description="Task type")
    content: str = Field(description="Task content")
    dependencies: List[str] = Field(
        default_factory=list, description="Dependent regular task IDs"
    )
    parallel_group_id: Optional[str] = Field(
        default=None, description="Dependent parallel task group ID"
    )
    result: Optional[Any] = Field(default=None, description="Task result")


# Parallel task group model (contains multiple parallel subtasks)
class ParallelTaskGroup(BaseModel):
    group_id: str = Field(
        description="Parallel task group ID (for dependent task association)"
    )
    subtasks: List[SubTask] = Field(description="Parallel subtasks within group")
    status: TaskStatus = Field(
        default=TaskStatus.PENDING, description="Overall group status"
    )


# Global state class
class GlobalState(BaseModel):
    model_config = ConfigDict(
        use_enum_values=True,
        arbitrary_types_allowed=True,
    )

    user_input: str = Field(description="User's original input")
    user_task_type: Optional[UserTaskType] = Field(
        default=None, description="User task type"
    )
    subtasks: List[SubTask] = Field(
        default_factory=list, description="Regular subtask list"
    )
    parallel_task_groups: Dict[str, ParallelTaskGroup] = Field(
        default_factory=dict, description="Parallel task groups (key=group_id)"
    )
    completed_tasks: Dict[str, SubTask] = Field(
        default_factory=dict, description="Completed regular tasks"
    )
    completed_parallel_groups: Dict[str, ParallelTaskGroup] = Field(
        default_factory=dict, description="Completed parallel task groups"
    )
    merged_result: Dict[str, Any] = Field(
        default_factory=dict, description="Merged results"
    )
    hitl_status: Optional[str] = Field(default=None, description="HITL status")
    file_paths: Dict[str, str] = Field(default_factory=dict, description="File paths")
    execution_plan: Optional[str] = Field(default=None, description="Execution plan")
    sandbox_dir: str = Field(description="Sandbox directory")
    use_react_executor: bool = Field(
        default=False, description="Use React executor for single task execution"
    )
    react_max_steps: int = Field(
        default=3, description="Max React executor steps per task"
    )
    use_react_supervisor: bool = Field(
        default=False, description="Use React supervisor for task classification"
    )
    supervisor_decision: Optional[str] = Field(
        default=None, description="Supervisor decision label"
    )
    supervisor_reasoning: Optional[str] = Field(
        default=None, description="Supervisor reasoning"
    )

    # CodeAct Todo List - for executor subgraph integration
    todo_list: Optional["TodoList"] = Field(
        default=None, description="CodeAct todo list for task execution"
    )

    # Preprocessing results - parameter table for the entire workflow
    session_id: Optional[str] = Field(
        default=None, description="Unique session ID for file management"
    )
    opensandbox_id: Optional[str] = Field(
        default=None, description="OpenSandbox instance ID"
    )
    sandbox_data_dir: Optional[str] = Field(
        default=None, description="Data directory in sandbox"
    )
    extracted_parameters: Dict[str, Any] = Field(
        default_factory=dict, description="Parameter table extracted from user input"
    )
    file_analyses: List[Dict[str, Any]] = Field(
        default_factory=list, description="File analysis results"
    )

    # ==================== Iterative Executor Additional Fields ====================

    # Iterative execution history
    iteration_history: List[Dict[str, Any]] = Field(
        default_factory=list, description="Iterative execution history (generated by IterativeExecutor)"
    )

    # Completed output files list
    completed_output_files: List[str] = Field(
        default_factory=list, description="Completed output file paths list"
    )

    # MCP tool call records
    mcp_call_records: List[Dict[str, Any]] = Field(
        default_factory=list, description="MCP tool call records"
    )

    # Thinking history - tracks LLM thinking process
    thinking_history: List[Dict[str, Any]] = Field(
        default_factory=list, description="LLM thinking process history"
    )

    # ==================== Init Node Additional Fields ====================

    # Files uploaded to shared directory
    uploaded_files: List[str] = Field(
        default_factory=list, description="File paths uploaded to sandbox shared directory"
    )

    # Conversation history (loaded from relational database)
    conversation_history: List[Dict[str, Any]] = Field(
        default_factory=list, description="Conversation history"
    )

    # Mem0 task history
    immunity_history: List[Dict[str, Any]] = Field(
        default_factory=list, description="Historical task results for this session in Mem0"
    )

    # ==================== HITL (Human-in-the-Loop) Additional Fields ====================

    # HITL iteration counter
    hitl_iteration: int = Field(default=0, description="HITL iteration counter")

    # User feedback content
    user_feedback: Optional[str] = Field(default=None, description="User feedback content")

    # Missing parameters
    missing_parameters: List[Dict[str, Any]] = Field(
        default_factory=list, description="Missing parameters"
    )

    # HITL confirmation status
    hitl_confirmed: bool = Field(default=False, description="HITL user confirmation status")

    # HITL request data
    hitl_request: Optional[Dict[str, Any]] = Field(
        default=None, description="HITL request data"
    )

    # HITL history
    hitl_history: List[Dict[str, Any]] = Field(
        default_factory=list, description="HITL history"
    )

    # HITL request data history
    hitl_request_history: List[Dict[str, Any]] = Field(
        default_factory=list, description="HITL request data history"
    )

    # HITL request data list
    hitl_requests: List[Dict[str, Any]] = Field(
        default_factory=list, description="HITL request data list"
    )

    # HITL response data
    hitl_response: Optional[Dict[str, Any]] = Field(
        default=None, description="HITL response data"
    )

    # HITL response data history
    hitl_response_history: List[Dict[str, Any]] = Field(
        default_factory=list, description="HITL response data history"
    )

    # HITL response data list
    hitl_responses: List[Dict[str, Any]] = Field(
        default_factory=list, description="HITL response data list"
    )

    # Parent state (for subgraphs)
    parent_state: Optional["GlobalState"] = Field(
        default=None, description="Parent state (for subgraphs)"
    )

    # Task markdown content
    task_md_content: Optional[str] = Field(
        default=None, description="Task markdown content"
    )

    def get_llm(
        self, purpose: str = "reasoning", node_name: Optional[str] = None, **kwargs
    ) -> Optional[Any]:
        """
        Get LLM instance (recommended method)

        Automatically uses self.progress_callback and self.session_id to create LLM,
        ensuring all thinking is properly captured and pushed.

        Args:
            purpose: Model purpose, options: "reasoning", "bioinformatics", "reasoning_advanced", "code"
            node_name: Node name, auto-inferred if not provided
            **kwargs: Additional parameters passed to LLM creation function

        Returns:
            LLM instance, or None if creation fails

        Examples:
            >>> llm = state.get_llm(purpose="reasoning", node_name="supervisor")
            >>> response = llm.invoke(messages)
        """
        from agent.utils.llm_factory import create_llm_with_thinking

        # Auto-infer caller node name
        if node_name is None:
            node_name = self._get_caller_node_name()

        # Get callback from global registry via session_id
        callback = None
        if self.session_id:
            try:
                import sys
                from pathlib import Path

                backend_dir = Path(__file__).parent.parent / "backend"
                project_root = backend_dir.parent

                if str(backend_dir) not in sys.path:
                    sys.path.insert(0, str(backend_dir))
                if str(project_root) not in sys.path:
                    sys.path.insert(0, str(project_root))

                from backend import progress_tracker as pt_module

                callback = pt_module.get_progress_callback(self.session_id)
                print(
                    f"[GlobalState.get_llm] Got callback for session {self.session_id}: {callback is not None}"
                )
            except (ImportError, AttributeError) as e:
                print(f"[GlobalState.get_llm] Failed to get callback: {e}")

        return create_llm_with_thinking(
            purpose=purpose,
            progress_callback=callback,
            session_id=self.session_id,
            node_name=node_name,
            **kwargs,
        )

    def _get_caller_node_name(self) -> str:
        """
        Auto-infer caller node name

        Infers node name by inspecting the call stack. If the function name ends with '_node',
        returns the name without the '_node' suffix.

        Returns:
            Inferred node name
        """
        import inspect

        try:
            frame = inspect.currentframe()
            if frame and frame.f_back and frame.f_back.f_back:
                func_name = frame.f_back.f_back.f_code.co_name
                if func_name.endswith("_node"):
                    return func_name.replace("_node", "")
        except Exception:
            pass
        return "unknown"

    def record_thinking(
        self,
        content: str,
        node_name: str,
        step_name: str = "reasoning",
        details: Optional[Dict[str, Any]] = None,
    ) -> None:
        """
        Record thinking to history

        Records LLM thinking process to the thinking_history field,
        for later querying and debugging.

        Args:
            content: Thinking content
            node_name: Node name
            step_name: Step name
            details: Additional details
        """
        record = {
            "timestamp": datetime.now().isoformat(),
            "node": node_name,
            "step": step_name,
            "content": content[:500] if len(content) > 500 else content,
            "session_id": self.session_id,
        }
        if details:
            record["details"] = details

        self.thinking_history.append(record)


# Lazy rebuild of GlobalState to resolve forward references (Pydantic v2 requirement)
# This is called when the todo_list field is first accessed with a TodoList object
_global_state_rebuilt = False


def ensure_global_state_rebuilt() -> None:
    """
    Ensure GlobalState model is rebuilt to resolve forward references.

    This must be called before using the todo_list field with a TodoList object.
    It's safe to call multiple times - subsequent calls are no-ops.

    Note: This also injects TodoList into the module's global namespace so that
    get_type_hints() can resolve the forward reference "TodoList" in GlobalState.
    """
    global _global_state_rebuilt, TodoList
    if _global_state_rebuilt:
        return

    try:
        from nodes.subagents.code_act.todo_list import TodoList as _TodoList

        # Inject TodoList into module global namespace so get_type_hints() can resolve forward references
        globals()["TodoList"] = _TodoList
        TodoList = _TodoList
        GlobalState.model_rebuild()
        _global_state_rebuilt = True
    except ImportError as e:
        # If TodoList cannot be imported, log warning but continue
        # The model will work but todo_list field will only accept dicts
        import warnings

        warnings.warn(f"Could not rebuild GlobalState with TodoList: {e}")


# Note: We don't call ensure_global_state_rebuilt() here to avoid import-time side effects.
# Instead, code that needs to use the todo_list field should call it explicitly.
