from typing import Dict, List, Any, Optional, TYPE_CHECKING, ForwardRef
from pydantic import BaseModel, Field, ConfigDict
from enum import Enum

if TYPE_CHECKING:
    from nodes.subagents.code_act.todo_list import TodoList


# User task type enum
class UserTaskType(str, Enum):
    """User task type"""
    GENERAL_QA = "GENERAL_QA"
    EXECUTE_PLAN = "EXECUTE_PLAN"
    IMMUNOLOGY_TASK = "IMMUNOLOGY_TASK"
    USE_HISTORY = "USE_HISTORY"

# Task status enum
class TaskStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    DEPENDENCY_WAIT = "dependency_wait"


# Parameter source enum - tracks where a parameter value came from
class ParameterSource(str, Enum):
    """Parameter source type for tracking parameter origin"""
    USER_INPUT = "user_input"      # Provided by user during preprocessing
    TASK_OUTPUT = "task_output"    # Generated by a task execution
    INFERRED = "inferred"          # Inferred by LLM from context
    DEFAULT = "default"            # Default value from tool definition


# Tagged parameter value - stores value with its source information
class TaggedParameterValue(BaseModel):
    """A parameter value with source tracking"""
    value: Any = Field(description="The actual parameter value")
    source: ParameterSource = Field(description="Where this value came from")
    source_task_id: Optional[str] = Field(default=None, description="Task ID if source is TASK_OUTPUT")
    description: Optional[str] = Field(default=None, description="Human-readable description of the parameter")
    data_type: Optional[str] = Field(default=None, description="Data type hint (e.g., 'binding_predictions', 'airr_results')")
    
    def __str__(self) -> str:
        return str(self.value)
    
    def __repr__(self) -> str:
        return f"TaggedValue({self.value}, source={self.source.value})"


# Single task model (added parallel_group_id to associate dependent parallel task groups)
class SubTask(BaseModel):
    model_config = ConfigDict(use_enum_values=True)
    
    task_id: str = Field(description="Unique task ID")
    task_type: UserTaskType = Field(description="Task type")
    content: str = Field(description="Task content")
    dependencies: List[str] = Field(default_factory=list, description="Dependent regular task IDs")
    parallel_group_id: Optional[str] = Field(default=None, description="Dependent parallel task group ID")
    result: Optional[Any] = Field(default=None, description="Task result")


# Parallel task group model (contains multiple parallel subtasks)
class ParallelTaskGroup(BaseModel):
    group_id: str = Field(description="Parallel task group ID (for dependent task association)")
    subtasks: List[SubTask] = Field(description="Parallel subtasks within group")
    status: TaskStatus = Field(default=TaskStatus.PENDING, description="Overall group status")


# Global state class
class GlobalState(BaseModel):
    model_config = ConfigDict(use_enum_values=True)
    
    user_input: str = Field(description="User's original input")
    user_task_type: Optional[UserTaskType] = Field(default=None, description="User task type")
    subtasks: List[SubTask] = Field(default_factory=list, description="Regular subtask list")
    parallel_task_groups: Dict[str, ParallelTaskGroup] = Field(default_factory=dict, description="Parallel task groups (key=group_id)")
    completed_tasks: Dict[str, SubTask] = Field(default_factory=dict, description="Completed regular tasks")
    completed_parallel_groups: Dict[str, ParallelTaskGroup] = Field(default_factory=dict, description="Completed parallel task groups")
    merged_result: Dict[str, Any] = Field(default_factory=dict, description="Merged results")
    hitl_status: Optional[str] = Field(default=None, description="HITL status")
    file_paths: Dict[str, str] = Field(default_factory=dict, description="File paths")
    execution_plan: Optional[str] = Field(default=None, description="Execution plan")
    sandbox_dir: str = Field(description="Sandbox directory")
    use_react_executor: bool = Field(default=False, description="Use React executor for single task execution")
    react_max_steps: int = Field(default=3, description="Max React executor steps per task")
    use_react_supervisor: bool = Field(default=False, description="Use React supervisor for task classification")
    supervisor_decision: Optional[str] = Field(default=None, description="Supervisor decision label")
    supervisor_reasoning: Optional[str] = Field(default=None, description="Supervisor reasoning")
    
    # CodeAct Todo List - for executor subgraph integration
    todo_list: Optional["TodoList"] = Field(default=None, description="CodeAct todo list for task execution")
    
    # Preprocessing results - parameter table for the entire workflow
    session_id: Optional[str] = Field(default=None, description="Unique session ID for file management")
    opensandbox_id: Optional[str] = Field(default=None, description="OpenSandbox instance ID")
    sandbox_data_dir: Optional[str] = Field(default=None, description="Data directory in sandbox")
    extracted_parameters: Dict[str, Any] = Field(default_factory=dict, description="Parameter table extracted from user input")
    file_analyses: List[Dict[str, Any]] = Field(default_factory=list, description="File analysis results")


# Lazy rebuild of GlobalState to resolve forward references (Pydantic v2 requirement)
# This is called when the todo_list field is first accessed with a TodoList object
_global_state_rebuilt = False

def ensure_global_state_rebuilt() -> None:
    """
    Ensure GlobalState model is rebuilt to resolve forward references.
    
    This must be called before using the todo_list field with a TodoList object.
    It's safe to call multiple times - subsequent calls are no-ops.
    """
    global _global_state_rebuilt
    if _global_state_rebuilt:
        return
    
    try:
        from nodes.subagents.code_act.todo_list import TodoList
        GlobalState.model_rebuild()
        _global_state_rebuilt = True
    except ImportError as e:
        # If TodoList cannot be imported, log warning but continue
        # The model will work but todo_list field will only accept dicts
        import warnings
        warnings.warn(f"Could not rebuild GlobalState with TodoList: {e}")


# Note: We don't call ensure_global_state_rebuilt() here to avoid import-time side effects.
# Instead, code that needs to use the todo_list field should call it explicitly.