"""
File Parameter Table for CodeAct Dynamic Parameter Inference

This module provides:
1. FileParameter: A single file entry with path and description
2. FileParameterTable: A collection of file parameters with management functions

The file parameter table is used by CodeAct to:
- Store known files (from user input, task outputs)
- Provide context for LLM parameter inference
- Track file provenance (which task produced which file)
"""

from typing import Dict, List, Any, Optional
from pydantic import BaseModel, Field, ConfigDict
from enum import Enum
from datetime import datetime
import json


class FileSource(str, Enum):
    """Source of the file parameter"""
    USER_INPUT = "user_input"       # File provided by user
    TASK_OUTPUT = "task_output"     # File generated by a task
    SYSTEM = "system"               # System file (e.g., benchmark data)


class FileParameter(BaseModel):
    """
    A single file parameter entry with metadata
    
    Attributes:
        key: Unique identifier for this file (e.g., "predictions_csv", "integrated_rds")
        path: Absolute file path
        description: Human-readable description of file contents
        source: Where this file came from (user_input, task_output, system)
        source_task_id: If task_output, which task produced this file
        file_type: File extension/type (csv, rds, fasta, etc.)
        created_at: When this entry was created
        metadata: Additional metadata (columns, row count, etc.)
    """
    model_config = ConfigDict(
        use_enum_values=True,
        validate_assignment=True
    )
    
    key: str = Field(description="Unique identifier for this file parameter")
    path: str = Field(description="Absolute file path")
    description: str = Field(description="Human-readable description of file contents")
    source: FileSource = Field(description="Source of the file")
    source_task_id: Optional[str] = Field(default=None, description="Task ID that produced this file")
    file_type: Optional[str] = Field(default=None, description="File type/extension")
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat())
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")


class FileParameterTable(BaseModel):
    """
    Collection of file parameters for a session
    
    This table is:
    - Initialized with user-provided files
    - Updated after each task execution with output files
    - Used by infer_parameters_node to determine parameter values
    
    Attributes:
        session_id: Session identifier
        files: Dictionary mapping key -> FileParameter
        updated_at: Last update timestamp
    """
    model_config = ConfigDict(
        validate_assignment=True
    )
    
    session_id: str = Field(description="Session identifier")
    files: Dict[str, FileParameter] = Field(default_factory=dict)
    updated_at: str = Field(default_factory=lambda: datetime.now().isoformat())
    
    def add_file(self, file_param: FileParameter) -> None:
        """Add or update a file parameter"""
        self.files[file_param.key] = file_param
        self.updated_at = datetime.now().isoformat()
    
    def get_file(self, key: str) -> Optional[FileParameter]:
        """Get a file parameter by key"""
        return self.files.get(key)
    
    def get_file_by_path(self, path: str) -> Optional[FileParameter]:
        """Get a file parameter by path"""
        for f in self.files.values():
            if f.path == path:
                return f
        return None
    
    def get_files_by_type(self, file_type: str) -> List[FileParameter]:
        """Get all files of a specific type"""
        return [f for f in self.files.values() if f.file_type == file_type]
    
    def get_files_by_source(self, source: FileSource) -> List[FileParameter]:
        """Get all files from a specific source"""
        return [f for f in self.files.values() if f.source == source]
    
    def get_files_from_task(self, task_id: str) -> List[FileParameter]:
        """Get all files produced by a specific task"""
        return [f for f in self.files.values() if f.source_task_id == task_id]
    
    def to_context_string(self) -> str:
        """
        Generate a human-readable string for LLM context
        
        Returns:
            Formatted string describing all available files
        """
        if not self.files:
            return "No files available in the parameter table."
        
        lines = ["Available files in the session:"]
        for key, f in self.files.items():
            source_info = f.source
            if f.source_task_id:
                source_info += f" (from task: {f.source_task_id})"
            
            lines.append(f"  - [{key}] {f.path}")
            lines.append(f"    Type: {f.file_type or 'unknown'}")
            lines.append(f"    Source: {source_info}")
            lines.append(f"    Description: {f.description}")
            
            # Include metadata if available
            if f.metadata:
                for meta_key, meta_val in f.metadata.items():
                    lines.append(f"    {meta_key}: {meta_val}")
        
        return "\n".join(lines)
    
    def to_markdown(self) -> str:
        """Generate markdown representation for todo-list.md"""
        if not self.files:
            return "## File Parameter Table\n\nNo files registered.\n"
        
        lines = [
            "## File Parameter Table",
            "",
            "| Key | Path | Type | Source | Description |",
            "|-----|------|------|--------|-------------|",
        ]
        
        for key, f in self.files.items():
            source = f.source
            if f.source_task_id:
                source += f" ({f.source_task_id})"
            lines.append(f"| {key} | {f.path} | {f.file_type or '-'} | {source} | {f.description} |")
        
        return "\n".join(lines) + "\n"
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization"""
        return {
            "session_id": self.session_id,
            "updated_at": self.updated_at,
            "files": {k: v.model_dump() for k, v in self.files.items()}
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "FileParameterTable":
        """Create from dictionary"""
        files = {}
        for k, v in data.get("files", {}).items():
            files[k] = FileParameter(**v)
        
        return cls(
            session_id=data.get("session_id", "unknown"),
            updated_at=data.get("updated_at", datetime.now().isoformat()),
            files=files
        )


# =============================================================================
# Helper Functions
# =============================================================================

def create_file_param_from_user_input(
    key: str,
    path: str,
    description: str,
    file_type: Optional[str] = None,
    metadata: Optional[Dict[str, Any]] = None
) -> FileParameter:
    """Create a FileParameter from user-provided file"""
    if file_type is None:
        file_type = path.split(".")[-1] if "." in path else "unknown"
    
    return FileParameter(
        key=key,
        path=path,
        description=description,
        source=FileSource.USER_INPUT,
        file_type=file_type,
        metadata=metadata or {}
    )


def create_file_param_from_task_output(
    key: str,
    path: str,
    description: str,
    task_id: str,
    file_type: Optional[str] = None,
    metadata: Optional[Dict[str, Any]] = None
) -> FileParameter:
    """Create a FileParameter from task output"""
    if file_type is None:
        file_type = path.split(".")[-1] if "." in path else "unknown"
    
    return FileParameter(
        key=key,
        path=path,
        description=description,
        source=FileSource.TASK_OUTPUT,
        source_task_id=task_id,
        file_type=file_type,
        metadata=metadata or {}
    )


def extract_file_info_from_task_result(
    task_id: str,
    task_description: str,
    task_result: Dict[str, Any]
) -> List[FileParameter]:
    """
    Extract file parameters from a completed task's result
    
    Args:
        task_id: ID of the completed task
        task_description: Description of the task
        task_result: Result dictionary from task execution
    
    Returns:
        List of FileParameter objects extracted from the result
    """
    file_params = []
    
    if not task_result:
        return file_params
    
    # Common output file keys to look for
    output_keys = [
        "output_file", "output_path", "result_file", "result_path",
        "predictions_file", "predictions_path", "predictions_csv",
        "integrated_file", "integrated_rds", "airr_file", "airr_path"
    ]
    
    for key in output_keys:
        if key in task_result:
            path = task_result[key]
            if isinstance(path, str) and path:
                # Extract file type
                file_type = path.split(".")[-1] if "." in path else "unknown"
                
                # Generate description based on task and file type
                description = f"Output from task '{task_description[:50]}'"
                if file_type == "csv":
                    description += " (CSV data file)"
                elif file_type == "rds":
                    description += " (RDS data file)"
                elif file_type == "fasta":
                    description += " (FASTA sequence file)"
                elif file_type == "tsv":
                    description += " (TSV data file)"
                
                file_param = create_file_param_from_task_output(
                    key=f"{task_id}_{key}",
                    path=path,
                    description=description,
                    task_id=task_id,
                    file_type=file_type
                )
                file_params.append(file_param)
    
    # Also check for nested output structure
    if "output" in task_result and isinstance(task_result["output"], dict):
        output = task_result["output"]
        for key, value in output.items():
            if isinstance(value, str) and ("/" in value or "\\" in value):
                # This looks like a file path
                file_type = value.split(".")[-1] if "." in value else "unknown"
                file_param = create_file_param_from_task_output(
                    key=f"{task_id}_{key}",
                    path=value,
                    description=f"Output '{key}' from task '{task_description[:30]}'",
                    task_id=task_id,
                    file_type=file_type
                )
                file_params.append(file_param)
    
    return file_params


# =============================================================================
# LLM Prompt Generation for Parameter Inference
# =============================================================================

def get_parameter_inference_prompt(
    tool_name: str,
    tool_description: str,
    tool_parameters: List[Dict[str, Any]],
    user_input: str,
    file_param_table: FileParameterTable,
    completed_tasks: List[Dict[str, Any]]
) -> str:
    """
    Generate LLM prompt for parameter inference
    
    Args:
        tool_name: Name of the tool to call
        tool_description: Description of the tool
        tool_parameters: List of parameter definitions
        user_input: Original user input
        file_param_table: Current file parameter table
        completed_tasks: List of completed task summaries
    
    Returns:
        Formatted prompt string for LLM
    """
    # Build file context
    file_context = file_param_table.to_context_string()
    
    # Build completed tasks context
    tasks_context = "Recently completed tasks:"
    if completed_tasks:
        for task in completed_tasks[-5:]:  # Last 5 tasks
            tasks_context += f"\n  - {task.get('id', 'unknown')}: {task.get('description', 'N/A')[:50]}"
            if task.get('result_summary'):
                tasks_context += f"\n    Result: {task['result_summary'][:100]}"
    else:
        tasks_context += "\n  No tasks completed yet."
    
    # Build parameter definitions
    params_context = "Tool parameters to fill:"
    for param in tool_parameters:
        param_name = param.get("name", "unknown")
        param_type = param.get("type", "any")
        param_desc = param.get("description", "")
        required = param.get("required", False)
        
        params_context += f"\n  - {param_name} ({param_type})"
        if required:
            params_context += " [REQUIRED]"
        if param_desc:
            params_context += f": {param_desc}"
    
    prompt = f"""You are a parameter inference expert. Your task is to determine the correct parameter values for a tool call based on available context.

# Tool Information
- Tool name: {tool_name}
- Description: {tool_description}

# Parameter Definitions
{params_context}

# Available Context

## User's Original Request
{user_input}

## {file_context}

## {tasks_context}

# Your Task
Analyze the above context and determine the appropriate parameter values for this tool call.

Rules:
1. For file parameters, use the exact file path from the File Parameter Table
2. If a parameter should come from a task output, reference the appropriate file from the table
3. If a required parameter cannot be determined, mark it as "NEEDS_USER_INPUT"
4. Only include parameters that have values to fill

# Output Format
Return a JSON object with the inferred parameters:
```json
{{
  "parameters": {{
    "param_name": "inferred_value",
    ...
  }},
  "inference_notes": "Brief explanation of how parameters were determined"
}}
```

Return only the JSON object, no additional text."""

    return prompt


# =============================================================================
# Test / Demo
# =============================================================================

if __name__ == "__main__":
    print("Testing File Parameter Table...")
    print("=" * 60)
    
    # Create a table
    table = FileParameterTable(session_id="test_session_001")
    
    # Add user input files
    table.add_file(create_file_param_from_user_input(
        key="meta_csv",
        path="/data/benchmark_data/tcr_icon_benchmark/260204_tcr_icon_metadata.csv",
        description="TCR benchmark metadata with sample information"
    ))
    
    table.add_file(create_file_param_from_user_input(
        key="meta_rds", 
        path="/data/benchmark_data/tcr_icon_benchmark/260204_tcr_icon_benchmark.rds",
        description="TCR benchmark RDS file with cell data"
    ))
    
    # Simulate task output
    table.add_file(create_file_param_from_task_output(
        key="task_001_predictions",
        path="/data/sessions/test_session_001/predictions.csv",
        description="NetTCR binding predictions for MART-1 epitope",
        task_id="task_001"
    ))
    
    # Print context string
    print("\n📄 File Parameter Table Context:")
    print("-" * 40)
    print(table.to_context_string())
    
    # Print markdown
    print("\n📝 Markdown Representation:")
    print("-" * 40)
    print(table.to_markdown())
    
    # Test parameter inference prompt
    print("\n🤖 Parameter Inference Prompt:")
    print("-" * 40)
    prompt = get_parameter_inference_prompt(
        tool_name="integrate_tcr_data_complete",
        tool_description="Integrate TCR data from CSV into RDS file",
        tool_parameters=[
            {"name": "input_csv", "type": "string", "required": True, "description": "CSV file to integrate"},
            {"name": "input_rds", "type": "string", "required": True, "description": "RDS file to merge into"},
        ],
        user_input="Run TCR analysis and evaluate predictions",
        file_param_table=table,
        completed_tasks=[
            {"id": "task_001", "description": "TCR prediction", "result_summary": "Generated predictions.csv"}
        ]
    )
    print(prompt)

